server:
  port: 10035
  servlet:
    context-path: /gallery

spring:
  application:
    name: gallery_manager_api
  profiles:
    active: local
  datasource:
    username: sa
    password: ''
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;MODE=Oracle;INIT=CREATE SCHEMA IF NOT EXISTS GALLERYDB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_schema: GALLERYDB
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    locations: classpath:db/migration

feign:
  placeholder:
    name: PLACEHOLDER-API
    rootUrl: https://jsonplaceholder.typicode.com/
    resources:
      users: users
      photos: photos
      albums: albums
      comments: comments
      posts: posts

security:
    enable: false