CREATE TABLE GALLERYDB.ROL(
    ID_ROL NUMBER(20,0) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_ROL)
);

CREATE SEQUENCE GALLERYDB.GALL_SEQ_ROL
    start with 1
    increment by 1
    maxvalue 99999
    minvalue 1;

CREATE TABLE GALLERYDB.USER_GALLERY(
    ID_USER NUMBER(20,0) NOT NULL,
    ID_ROL NUMBER(20,0),
    USER_NAME VARCHAR(50),
    PASSWORD VARCHAR(60),
    PRIMARY KEY (ID_USER),
    CONSTRAINT ID_ROL_FK
        FOREIGN KEY (ID_ROL)
            REFERENCES GALLERYDB.ROL (ID_ROL)
);

CREATE TABLE GALLERYDB.ALBUM(
    ID_ALBUM NUMBER(20,0) NOT NULL,
    ID_USER NUMBER(20,0) NOT NULL,
    PRIMARY KEY (ID_ALBUM),
    CONSTRAINT ID_USER_ALBUM_FK
        FOREIGN KEY (ID_USER)
            REFERENCES GALLERYDB.USER_GALLERY (ID_USER)
);

CREATE TABLE GALLERYDB.ACCESS(
    ID_ACCESS NUMBER(20,0) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_ACCESS)
);

CREATE SEQUENCE GALLERYDB.GALL_SEQ_ACCESS
    start with 1
    increment by 1
    maxvalue 99999
    minvalue 1;

CREATE TABLE GALLERYDB.SHARE(
    ID_ALBUM NUMBER(20,0) NOT NULL,
    ID_ACCESS NUMBER(20,0) NOT NULL,
    ID_USER NUMBER(20,0),
    CONSTRAINT ID_ALBUM_FK
        FOREIGN KEY (ID_ALBUM)
            REFERENCES GALLERYDB.ALBUM (ID_ALBUM),
    CONSTRAINT ID_ACCESS_FK
        FOREIGN KEY (ID_ACCESS)
            REFERENCES GALLERYDB.ACCESS (ID_ACCESS),
    CONSTRAINT ID_USER_SHARE_FK
        FOREIGN KEY (ID_USER)
            REFERENCES GALLERYDB.USER_GALLERY (ID_USER)
);