
INSERT INTO GALLERYDB.ROL(ID_ROL,NAME) VALUES(GALLERYDB.GALL_SEQ_ROL.NEXTVAL,'ROLE_ADMIN');

INSERT INTO GALLERYDB.ACCESS(ID_ACCESS,NAME) VALUES(GALLERYDB.GALL_SEQ_ACCESS.NEXTVAL,'READ');
INSERT INTO GALLERYDB.ACCESS(ID_ACCESS,NAME) VALUES(GALLERYDB.GALL_SEQ_ACCESS.NEXTVAL,'NOT_ACCESS');

INSERT INTO GALLERYDB.USER_GALLERY(ID_USER,ID_ROL,USER_NAME,PASSWORD) VALUES(100,(SELECT ID_ROL FROM GALLERYDB.ROL WHERE NAME='ROLE_ADMIN'),'admin','$2a$10$yegAyWqnpZvWLo2x.A921OypbUipqZNk/W46mBonQinlWlPQgW7Fm');